### ISSUE TITLE
Coordination: components and general requirements 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/pi-ui#1]
This issue compiles a list of the required components and other general requirements for the pi-ui library. This library should comply with this [design specs](https://xd.adobe.com/spec/bc1e9ea4-9d6c-475a-741d-11f6a7e5d0eb-ca2f/).

This guide is separated by components. Each component in the list has a WCBF which stands for "Where can be found"  in the design specs. The other bullets specify other minimal functional requirements of the component.

### Atomic UI Components 

- [x] **Tooltip**
   WCBF: hovering the voting progress bar 
- [ ] **Mardkown text editor**
    WCBF: submit proposal page / comments area
    **Done on politeiagui**
- [ ] **Comment & Comments tree**
    WCBF: proposal detail
    **Done on politeiagui**
- [ ] **Select box**
    WCBF: Sort comments
    **Done on politeiagui**
- [x] **Dropdown**
   WCBF: Under username in the header (missing design spec)
- [x] **Text input**
    WCBF: Inputs from login and signup forms
    - Errored/Valid state

- [x] **Search input box**
    WCBF: search vote tickets
    - Errored state
- [x] **Button**
     WCBF: submit button for login/signup forms
    - Handy primary and secondary options accordingly to the theme provided
- [x] **Card**
    WCBF: proposal cards
- [x] **Tab selector**
   WCBF: public proposal tabs
- [x] **Table**
   WCBF: Account history
- [x] **Status tags**
  WCBF: proposals cards status (approved, rejected, pending, etc)
- [x] **Link**
   WCBF: bottom of login/signup forms
- [x] **Icon**
  WCBF: proposal cards: comments link and github link
  - A JSX tag with ease specification of the available icons.
- [x] **Message**
   WCBF: submit page error / cannot submit comments message
   - Error/Info/Warning
- [x] **Modal**
   WCBF: welcome modal / purchase credits modal
- [x] **Progress bar**
   WCBF: proposal cards voting results

### Integration Components

- [x] **useTheme**
    - A react hook that updates CSS properties according to the theme passed.

### Layout components
- [x] **Grid**
    - A functional grid system to create responsive views easily.
- [x] **Header**
    - A simple and customisable header.
- [x] **Sidebar**
    - A simple and customisable sidebar.
- [x] **Main Section**
    - A wrapper for the app main section.
- [x] **Top Banner**
    - A wrapper for the top banner section.

### Resources
 - Design specs: https://xd.adobe.com/spec/bc1e9ea4-9d6c-475a-741d-11f6a7e5d0eb-ca2f/
 - Politeia redesign master issue: https://github.com/decred/dcrdesign/issues/77

**Comment by tiagoalvesdulce** [comment]
Closing 'cause we achieved completion of all the components listed. To request additional components open a new issue.
