### ISSUE TITLE
Update RadioButton style accordingly to design specs

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/pi-ui#133]
The RadioButton needs to be modified accordingly to the design specs:
https://xd.adobe.com/spec/4e7eb732-a445-46b0-4f7e-4152097a10c8-384f/screen/c878836b-546e-40f1-89c2-57911c2c3161/Proposals-admin-search-1

**Comment by amassarwi** [comment]
@fernandoabolafio should this be done with only css or we have .svg icons for checked/unchecked modes ? 🤔

**Comment by fernandoabolafio** [comment]
CSS preferably
