### ISSUE TITLE
Granular layout components 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/pi-ui#16]
We need some granular layout components to build custom "on-demand" layouts in the consumer repository. Those parts need to be based in the grid system to be responsive when composed. Something Like:
```jsx
<Col width={3}>one third length col</Col>
<Col width={3}>one third length col</Col>
<Col width={6}>half length col</Col>
```

**Comment by victorgcramos** [comment]
Implemented on https://github.com/decred/pi-ui/pull/442
