### ISSUE TITLE
Login and signup form are too narrow

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/pi-ui#165]
The changes applied to #158 made the login/signup forms too narrow:
Before:
![Screen Shot 2019-10-04 at 11 57 56](https://user-images.githubusercontent.com/14864439/66199217-71348780-e69e-11e9-8af3-e4a6780a6380.png)
After 158:
![Screen Shot 2019-10-04 at 11 58 31](https://user-images.githubusercontent.com/14864439/66199222-72fe4b00-e69e-11e9-8c68-ad9b073282dc.png)

**Comment by tiagoalvesdulce** [comment]
Fixed
