### ISSUE TITLE
[RadioButton] Improve disabled indicator

### ISSUE THREAD

**Issue by amass01** [decred/pi-ui#267]
As part of https://github.com/decred/pi-ui/pull/266 we added the following disabled indicator:
![image](https://user-images.githubusercontent.com/10324528/83528667-b0470100-a4e9-11ea-9859-12b07cb43455.png)

Would be nice if we get a design and improve this a bit, [here](https://mdbootstrap.com/docs/jquery/forms/radio-button/#:~:text=Bootstrap%20radio%20button,used%20for%20selecting%20multiple%20options) are some examples which include some nice grayish colors.

**Comment by amassarwi** [comment]
fyi - @linnutee
