### ISSUE TITLE
[CopyableText] Add round corners - border radius

### ISSUE THREAD

**Issue by amassarwi** [decred/pi-ui#276]
For now it looks like the following:
![image](https://user-images.githubusercontent.com/10324528/84319748-ca7b8180-ab70-11ea-8944-8974680ee555.png)

I would suggest aligning it with round corners we have around some *highlighted* text (e.h userid and pubkey in pigui account's page):
![image](https://user-images.githubusercontent.com/10324528/84319892-129aa400-ab71-11ea-964b-b4301bf0ef63.png)

Actually this kind of highlighting is used also on decrediton so maybe we should make it our standard component and use it over the place with one align styling.

**Comment by hamurabiaraujo** [comment]
On it.
