### ISSUE TITLE
[Tooltip] Tooltip overlapping inputs

### ISSUE THREAD

**Issue by victorgcramos** [decred/pi-ui#278]
This happens on invoice for invalid cells rendering. The tooltip overlaps the input so we are not able to move the cursor. 

As reported by @vctt94 on https://github.com/decred/politeiagui/issues/2005

![cell-cursor-errored](https://user-images.githubusercontent.com/22639213/84711575-0fbafd00-af3d-11ea-99d2-a21bca2ab5fd.gif)

**Comment by tiagoalvesdulce** [comment]
We are not using tooltips to wrap inputs anymore
