### ISSUE TITLE
[component] Copy to clipboard

### ISSUE THREAD

**Issue by thi4go** [decred/pi-ui#279]
I think a CopyToClipboard component would be a nice addition to pi-ui. Currently, pgui and decrediton implement their own, in which they share many similarities. Would be nice to have this standardized on our UI lib for other repos to use it.

**Comment by amassarwi** [comment]
Totally agree.
We have already `CopyableText`, and I thought latest exactly the same mate: https://github.com/decred/pi-ui/issues/276

I think we could use it, and delete any other implementation in both apps.

**Comment by amassarwi** [comment]
ref: https://github.com/decred/pi-ui/blob/master/src/components/CopyableText/CopyableText.jsx

**Comment by thi4go** [comment]
Oh great that this is tracked already mate :) will be closing this issue then.
