### ISSUE TITLE
[checkbox] Adjust component to match decrediton's checkboxes 

### ISSUE THREAD

**Issue by amass01** [decred/pi-ui#291]
We would like to use the `Checkbox` component in decrediton, to able to do that we will need to make 2 small adjustments:

1. Add description prop in order to show some more information about the checkbox
2. Make existing `label` prop from type `node` instead of `string` to be able to use translated content which is
not plain string.

See https://github.com/decred/decrediton/issues/2661

**Comment by tiagoalvesdulce** [comment]
Closed by https://github.com/decred/pi-ui/pull/294
