### ISSUE TITLE
[Tooltip] Tooltip is not displayed on hover

### ISSUE THREAD

**Issue by guilhermemntt** [decred/pi-ui#295]
When trying to fix https://github.com/decred/decrediton/pull/2605, it seems that ``pi-ui`` tooltip is not displaying in certain screen dimensions. It's been tested in https://github.com/decred/decrediton/pull/2603 too, and maybe it's related to https://github.com/decred/decrediton/pull/2605#pullrequestreview-455798236. I'd like to open this matter to discussion, since it affects not only Decrediton, but all other projects where ``pi-ui`` is used.

At the file ``src/components/Tooltip/styles.css``, behaviour on hover is defined as:

```
/* Media query to target devices with bigger screens */
@media screen and (min-width: 1025px) {
  .tooltip:hover .tooltipContent {
    visibility: visible;
    opacity: 1;
  }
}
```

Widths below 1025px will not be affected by this ``CSS`` rule.

**Comment by tiagoalvesdulce** [comment]
The default behavior for small screens is to show on click.

**Comment by guilhermemntt** [comment]
Closing this issue, as this is the desired behaviour and not a issue properly speaking.
