### ISSUE TITLE
[Layout] Sidebar looks weird for 14" displays

### ISSUE THREAD

**Issue by victorgcramos** [decred/pi-ui#296]
Reported by @lukebp on https://github.com/decred/politeiagui/issues/2140 and I think this should be brought here.

The current layout system creates a 10-2 proportion on the screen for the sidebar when the width is greater than 1400px. I think this resolution is too small, since the min column width would be 116.6px. See:

https://github.com/decred/pi-ui/blob/7b9e38f8964cd504245846fcf92f45871bcbab46/src/components/Layout/styles.css#L53

I'd suggest to change the min column width to 130px (min-width 1560px), so we can have enough space to fit a text content without having any visual issues.

![sidebar-collapsed](https://user-images.githubusercontent.com/9039877/94155249-5aa1b600-fe44-11ea-959c-b3c57fb701a0.png)

This looks way better, IMO (1560px):
<img width="1328" alt="Screen Shot 2020-09-24 at 2 31 06 PM" src="https://user-images.githubusercontent.com/22639213/94179963-ab7cd300-fe73-11ea-8ab4-e5b6f1105b10.png">

**Comment by brunaazambuja** [comment]
On this!
