### ISSUE TITLE
[CopyableText] extends compent class

### ISSUE THREAD

**Issue by fguisso** [decred/pi-ui#299]
I'm using this component in the [decrediton#2641](https://github.com/decred/decrediton/pull/2641) and I the style don't apply to child elements, my solution, seens not so good:
```
<CopyableText className={my_new_style}>testing</CopyableText>

.my_new_style span {
    ...
}
```

Maybe you can create somenthing like this:
```
<CopyableText spanStyle={my_new_span} buttonStyle={my_new_button_style} ...>testing</CopyableText>
```

**Comment by tiagoalvesdulce** [comment]
We'll be implementing this since people can choose between both approaches. I personally prefer the first one since you can stick to CSS. The second one you have to write JS objects. We can add both `spanStyle` and `spanClassName` so we have all the options available.
