### ISSUE TITLE
[TextInput] label doesn't accept FormattedMessage

### ISSUE THREAD

**Issue by fguisso** [decred/pi-ui#300]
I'm trying to use `<TextInput>` on Decrediton:
```jsx
import { FormattedMessage as T } from "react-intl";
...
<TextInput
    label={<T id="ln.watchtowersTab.Pubkey" m="Tower ID" />}
    id="towerID"
    ....
/>
```

Every works fine, but I get this message in console:

```diff
- Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `TextInput`, expected `string`.
```

**Comment by tiagoalvesdulce** [comment]
This should be fixed for all components that currently receive strings for labels, placeholders, etc. In order to do that the propType of them should be `node` instead of `string`
