### ISSUE TITLE
[RadioButton] Centralize button check indicator

### ISSUE THREAD

**Issue by victorgcramos** [decred/pi-ui#301]
The dot should be centralized.

<img width="493" alt="Screen Shot 2020-10-17 at 1 39 25 PM" src="https://user-images.githubusercontent.com/22639213/96348388-bd225680-107e-11eb-9065-b125eaa10e84.png">

**Comment by victorgcramos** [comment]
I can manage this in order to complete the work for https://github.com/decred/decrediton/issues/2702

**Comment by amassarwi** [comment]
Hey mate, 
I had the  same issue in decrediton, it's related to the `box-sizing` css property.

I ended up adding a wrapper to override decrediton's css, please have a look at the vote choices in the proposal details in decrediton. you might be able to solve that just with css from decrediton side.

**Comment by amassarwi** [comment]
ping: @victorgcramos

**Comment by victorgcramos** [comment]
Thanks for the feedback @amassarwi! I'll use that on decrediton side. But I think we should improve the way we handle this component, to work independent from outside changes, in order to keep the consistency. What do you think?

**Comment by amassarwi** [comment]
I totally agree. this would be ideal.
