### ISSUE TITLE
Datepicker: Support dynamic range.

### ISSUE THREAD

**Issue by amass01** [decred/pi-ui#342]
Currently if a the range updates dynamically the date picker still displaying the first calendar printed.
I would expect the date picker to display a new calendar which the updated range.

**Comment by lukebp** [comment]
If you cycle through the months and get to December, you can no longer keep going.  I would expect it to allow you to move to January of the next year.  Is this the same issue?

**Comment by amass01** [comment]
Not really, this is more about updating the possible dates when the settings for that changes.

Currently setting min/max dates is set on init and not updates afterwards even tho the datepicker accept the range as param, thus it should update/rerender if the provided range changes programmatically.

The issue you describing is different and worth oppening a new issue to track it down.

**Comment by lukebp** [comment]
Ok, I'll open a new one.

**Comment by vibros68** [comment]
I am on this issue
