### ISSUE TITLE
Icons: update clickable icons

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/pi-ui#387]
<img width="623" alt="Screen Shot 2021-11-16 at 11 03 51" src="https://user-images.githubusercontent.com/13955303/141999633-18e93ab1-bff8-49f4-8fa0-40effab77af5.png">

**Comment by tiagoalvesdulce** [comment]
This is already implemented on Decrediton but we don't have a component for it on pi-ui. This could be interesting for politeiagui too. Here are the places I can think of:

<img width="1280" alt="Screen Shot 2021-11-24 at 14 20 15" src="https://user-images.githubusercontent.com/13955303/143285976-c8d69ca8-542e-4778-aa1d-d6dda628a86e.png">

What do you think @lukebp ?

**Comment by lukebp** [comment]
@tiagoalvesdulce yeah, I agree.
