### ISSUE TITLE
CopyableText: change color and font weight

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/pi-ui#390]
<img width="750" alt="Screen Shot 2021-11-16 at 11 08 05" src="https://user-images.githubusercontent.com/13955303/142000266-719a7c7b-43d6-4a9c-8830-d64253440e2e.png">

**Comment by tiagoalvesdulce** [comment]
Decrediton related. Although this can be implemented in pi-ui by creating a new component for the text part of CopyableText and exporting it so Decrediton can import and use it. @bgptr are you interested in working on this?

**Comment by bgptr** [comment]
@tiagoalvesdulce Sure
