### ISSUE TITLE
Correctly handle font assets

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/pi-ui#59]
Right now we are bundling the font assets into javascript bundle and this isn't working for clients of this lib to have the font loaded. After spending a good amount of time on this problem I think we have two solutions available:
 - Export the static assets and delegate to the consumer to import it as it, please. In that case, we copy the static assets we want the client to import into the dist folder.
- Add an option in the `useTheme` function to specify the font assets. That way, the consumer can import whatever font he wants and then pass the paths into the useTheme function which will then correctly link then with the library. Something along the lines:
```js
const useTheme = (theme, fontSources) => {
    ...
}
```
Where the `fontSources` something like:
```js
{
 regular: "fontSourcePathRegular",
 semiBold: "fontSourcePathString"
 light: "fontSourcePathLight"
}
```
Then from this `fontSources` object, the lib can generate the font-faces accordingly.

**Comment by amassarwi** [comment]
On it
